import { normalizeSkillList } from "@/lib/resume/skills";

export const commonCourses = [
  "Accounting",
  "Advanced Database Systems",
  "Advanced Algorithms",
  "Aerodynamics",
  "AI Ethics",
  "Agile Software Development",
  "Algorithms",
  "Analysis of Algorithms",
  "Analog Electronics",
  "Android App Development",
  "Applied Calculus",
  "Applied Cryptography",
  "Applied Data Science",
  "Applied Linear Algebra",
  "Applied Machine Learning",
  "Applied Probability",
  "Artificial Intelligence",
  "Automata Theory",
  "Blockchain Technologies",
  "Big Data Analytics",
  "Business Analytics",
  "Business Communication",
  "Business Intelligence",
  "Calculus I",
  "Calculus II",
  "Calculus III",
  "Chemical Process Control",
  "Circuit Analysis",
  "Civil Engineering Materials",
  "Cloud Computing",
  "Cloud Security",
  "Compiler Construction",
  "Computer Architecture",
  "Computer Vision",
  "Computer Graphics",
  "Computer Networks",
  "Computer Organization",
  "Computer Programming",
  "Concurrent Programming",
  "Control Systems",
  "Cybersecurity Fundamentals",
  "Data Analytics",
  "Data Communication",
  "Data Engineering",
  "Data Mining",
  "Data Science",
  "Data Visualization",
  "Data Structures",
  "Database Systems",
  "Deep Learning",
  "Design and Analysis of Algorithms",
  "Design Patterns",
  "DevOps",
  "Differential Equations",
  "Digital Logic Design",
  "Digital Signal Processing",
  "Discrete Mathematics",
  "Distributed Systems",
  "Entrepreneurship",
  "Electric Machines",
  "Embedded Systems",
  "Engineering Economics",
  "Enterprise Systems",
  "Financial Accounting",
  "Finite Element Analysis",
  "Fluid Mechanics",
  "Full Stack Web Development",
  "Game Development",
  "Generative AI",
  "Geographic Information Systems",
  "Heat Transfer",
  "Human Computer Interaction",
  "Image Processing",
  "Information Security",
  "Information Retrieval",
  "Internet of Things",
  "iOS App Development",
  "Introduction to Programming",
  "Linear Control Systems",
  "Linear Algebra",
  "Machine Learning",
  "Management Information Systems",
  "Marketing Management",
  "Manufacturing Processes",
  "Materials Science",
  "Mechanics of Materials",
  "Microcontrollers",
  "Mobile Application Development",
  "Natural Language Processing",
  "Network Security",
  "Network Programming",
  "Numerical Methods",
  "Object Oriented Programming",
  "Operating Systems",
  "Operations Research",
  "Parallel Computing",
  "Power Systems",
  "Probability and Statistics",
  "Product Management",
  "Project Management",
  "Quality Assurance",
  "Reinforced Concrete Design",
  "Requirements Engineering",
  "Robotics",
  "Secure Software Development",
  "Simulation and Modeling",
  "Software Architecture",
  "Software Engineering",
  "Software Project Management",
  "Software Quality Assurance",
  "Software Requirements Engineering",
  "Structural Analysis",
  "System Design",
  "Systems Programming",
  "Theory of Computation",
  "Thermodynamics",
  "Transportation Engineering",
  "UI/UX Design",
  "Web Application Security",
  "Web Engineering",
];

export const commonSkills = [
  "A/B Testing",
  ".NET",
  "AWS",
  "AWS Lambda",
  "Agile",
  "Android",
  "Angular",
  "Ansible",
  "Apache Kafka",
  "Apollo GraphQL",
  "Azure",
  "Azure DevOps",
  "C",
  "C#",
  "C++",
  "CI/CD",
  "CSS",
  "Cypress",
  "D3.js",
  "Django",
  "Docker",
  "Drizzle",
  "Elasticsearch",
  "Electron",
  "Express.js",
  "FastAPI",
  "Figma",
  "Firebase",
  "Flask",
  "Flutter",
  "Git",
  "GitHub Actions",
  "GitLab CI",
  "Google Cloud",
  "Go",
  "GraphQL",
  "HTML",
  "HTML5",
  "JIRA",
  "Java",
  "JavaScript",
  "Jest",
  "Jupyter",
  "Keras",
  "Kubernetes",
  "LangChain",
  "Linux",
  "MATLAB",
  "Material UI",
  "Microsoft Azure",
  "Microsoft Excel",
  "Microsoft PowerPoint",
  "MongoDB",
  "Mongoose",
  "MySQL",
  "Next.js",
  "NestJS",
  "NoSQL",
  "Node.js",
  "NumPy",
  "OpenCV",
  "Oracle",
  "Pandas",
  "Playwright",
  "PostgreSQL",
  "Postman",
  "Power BI",
  "Prisma",
  "Product Management",
  "Python",
  "PyTorch",
  "R",
  "React",
  "React Native",
  "Redis",
  "REST APIs",
  "Redux",
  "Responsive Web Design",
  "Rust",
  "SAP",
  "Sass",
  "Scikit-learn",
  "Selenium",
  "SQL",
  "SQLite",
  "Supabase",
  "Tableau",
  "Tailwind CSS",
  "TanStack Query",
  "Terraform",
  "TensorFlow",
  "Three.js",
  "TypeScript",
  "UX Research",
  "Unit Testing",
  "Vercel",
  "Vite",
  "Vue.js",
  "WebRTC",
  "WebSockets",
  "WordPress",
  "Zustand",
  "iOS",
];

const skillGroups: Record<string, string[]> = {
  "Programming Languages": ["c", "c#", "c++", "go", "java", "javascript", "python", "r", "rust", "typescript"],
  Frontend: ["angular", "css", "d3.js", "figma", "html", "html5", "material ui", "next.js", "react", "redux", "responsive web design", "sass", "tailwind css", "three.js", "vite", "vue.js", "zustand"],
  Backend: [".net", "apollo graphql", "django", "drizzle", "express.js", "fastapi", "flask", "graphql", "mongoose", "nestjs", "node.js", "postman", "prisma", "rest apis", "tanstack query", "webrtc", "websockets"],
  Mobile: ["android", "flutter", "ios", "react native"],
  Databases: ["elasticsearch", "firebase", "mongodb", "mysql", "nosql", "oracle", "postgresql", "redis", "sql", "sqlite", "supabase"],
  "AI/ML": ["jupyter", "keras", "langchain", "machine learning", "numpy", "opencv", "pandas", "pytorch", "scikit-learn", "tensorflow"],
  "Cloud/DevOps": ["ansible", "aws", "aws lambda", "azure", "azure devops", "ci/cd", "docker", "github actions", "gitlab ci", "google cloud", "kubernetes", "linux", "microsoft azure", "terraform", "vercel"],
  "Data/Analytics": ["a/b testing", "matlab", "microsoft excel", "power bi", "tableau"],
  Testing: ["cypress", "jest", "playwright", "selenium", "unit testing"],
  "Product/Business": ["agile", "jira", "microsoft powerpoint", "product management", "sap", "ux research"],
};

export function filterOptions(options: string[], query: string): string[] {
  const normalized = query.trim().toLowerCase();

  if (!normalized) {
    return options.slice(0, 12);
  }

  return options
    .filter((option) => option.toLowerCase().includes(normalized))
    .slice(0, 12);
}

export function addUniqueValue(values: string[], value: string): string[] {
  const trimmed = value.trim();

  if (!trimmed) {
    return values;
  }

  if (values.some((item) => item.toLowerCase() === trimmed.toLowerCase())) {
    return values;
  }

  return normalizeSkillList([...values, trimmed]);
}

export function autoGroupSkills(skills: string[]) {
  const grouped = Object.entries(skillGroups)
    .map(([name, groupSkills]) => ({
      id: `skills-${name.toLowerCase().replaceAll(/[^a-z0-9]+/g, "-")}`,
      name,
      skills: normalizeSkillList(skills.filter((skill) => groupSkills.includes(skill.toLowerCase()))),
    }))
    .filter((group) => group.skills.length > 0);
  const used = new Set(grouped.flatMap((group) => group.skills.map((skill) => skill.toLowerCase())));
  const other = normalizeSkillList(skills.filter((skill) => !used.has(skill.toLowerCase())));

  return other.length ? [...grouped, { id: "skills-other", name: "Other", skills: other }] : grouped;
}
